archives:
  - id: terraform-provider-cassandra_v{{.Version}}-{{.Arch}}
    format: zip
    files:
      - none*
before:
  hooks:
    - go mod download
builds:
    - binary: terraform-provider-cassandra_v{{.Version}}
      goarch:
        - '386'
        - amd64
        - arm
        - arm64
      goos:
        - darwin
        - freebsd
        - linux
        - windows
changelog:
  skip: true
env:
  - CGO_ENABLED=0
